### PR TITLE
Attendance misc

### PR DESCRIPTION
**Pull request by kasimebrahim**
Attendance as per #18 

USAGE
<pre>
System.out.println("findAttendancesOf a student:\n" + attendanceService.findAttendancesOf(student.getId()));
System.out.println("find attendances of a course :\n" + attendanceService.findAttendancesByCourse(course.getId()));
System.out.println("findAttendancesOf a student in Course:\n" + attendanceService.findAttendancesOfByCourse(student.getId(), course.getId()));
System.out.println("find attendance by course offering:\n" + attendanceService.findAttendancesByCourseOffering(courseOffering.getId()));
System.out.println("find attendance of student by course offering:\n" + attendanceService.findAttendancesOfByCourseOffering(student.getId(), courseOffering.getId()));
</pre>

### CODE REVIEW

**Comment by JaCkIsO** [comment]
> @JaCkIsO any clue why this isn't working on the CI?

It's failing while Loading Dummy CourseOfferings. Says Faculty is detached. Faculty has CascadeType.PERSIST works when I change it to CascadeType.MERGE

**Comment by kasimebrahim** [comment]
@JaCkIsO got it. should work now.

**Comment by JaCkIsO** [comment]
@kasimebrahim I wanted @albahrawy's eyes on this. he was thinking of something of like this

**Comment by kasimebrahim** [comment]
> > @JaCkIsO any clue why this isn't working on the CI?
> 
> It's failing while Loading Dummy CourseOfferings. Says Faculty is detached. Faculty has CascadeType.PERSIST works when I change it to CascadeType.MERGE

Oh there is a merge? I didn't see this when I found out the looping cascade persist. Let me try merge

**Comment by JaCkIsO** [comment]
@kasimebrahim  I'm guessing since the Courses exist already, a CascadeType.MERGE would be appropriate. And CascadeType.ALL would have been more appropriate but it doesn't work weirdly enough

**Comment by kasimebrahim** [comment]
will come back with a more complete feature.

**Pull request closed without merging**
